### ISSUE TITLE
Week 7 : Schedule mandatory 60 minute dry run of team presentation the week of September 23

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/f2019_team-2#38]
@akallish can meet with teams in the late afternoon or early evening at the Kaplan Institute. Send Adam a few times and dates to choose from.

**Comment by luisasiliprandi** [comment]
@jzhong8  @lavanyajulaniya @yoichikanayama When are you available? 

I can on Monday or Tuesday afternoon/evening.

**Comment by jzhong8** [comment]
@luisasiliprandi @lavanyajulaniya @yoichikanayama 
I can do Tuesday afternoon. Thanks!

**Comment by yoichikanayama** [comment]
@luisasiliprandi @jzhong8 @lavanyajulaniya 

I am available on Mon, Tue afternoon or Wed.

**Comment by lavanyajulaniya** [comment]
I am free post 3.45pm on Tuesday afternoon and free all day on Wednesday. @luisasiliprandi @jzhong8 @yoichikanayama

**Comment by lavanyajulaniya** [comment]
Or between 12 noon to 2.45pm on tuesday too can work./

**Comment by luisasiliprandi** [comment]
@akallish can we meet on Tuesday around 4pm?
